/*
 * $Id$
 * --------------------------------------------------------------------------------------
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

package org.mule.ide.project.internal.runtime;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import org.eclipse.core.resources.IResource;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Preferences;
import org.mule.ide.project.MuleIdeProject;

public class ProjectPreferences extends Preferences
{
    private static final String CONFIG_FILE = "ConfigFile";
    private static final String HOT_DEPLOYMENT_NAME = "HotDeploymentName";

    private MuleIdeProject project;

    public ProjectPreferences(MuleIdeProject project)
    {
        super();
        this.project = project;
        setDefault(HOT_DEPLOYMENT_NAME, project.getName());
    }

    public void loadFromFile(File preferencesFile)
    {
        if (preferencesFile.exists() == false)
        {
            return;
        }

        InputStream input = null;
        try
        {
            input = new FileInputStream(preferencesFile);
            load(input);
        }
        catch (IOException iox)
        {
            throw new RuntimeException(iox);
        }
        finally
        {
            if (input != null)
            {
                try
                {
                    input.close();
                }
                catch (IOException iox)
                {
                    // ignore
                }
            }
        }
    }

    public void storeToFile(File preferencesFile)
    {
        OutputStream output = null;
        try
        {
            output = new FileOutputStream(preferencesFile);
            store(output, "Preferences generated by Mule IDE");
        }
        catch (IOException iox)
        {
            throw new RuntimeException(iox);
        }
        finally
        {
            if (output != null)
            {
                try
                {
                    output.close();
                }
                catch (IOException iox)
                {
                    // ignore
                }
            }
        }
    }

    public String getHotDeploymentName()
    {
        return getString(HOT_DEPLOYMENT_NAME);
    }

    public void setHotDeploymentName(String newName)
    {
        setValue(HOT_DEPLOYMENT_NAME, newName);
    }

    // TODO this can be more than one config file
    public IResource getConfigFile()
    {
        String path = getString(CONFIG_FILE);
        if ((path != null) && (path.length() > 0))
        {
            return project.getJavaProject().getProject().findMember(path);
        }
        return null;
    }

    public File getAbsolutePathToConfigFile()
    {
        IResource configResource = getConfigFile();
        if (configResource == null)
        {
            return null;
        }

        String configPath = configResource.getProjectRelativePath().toString();
        File configFile = new File(project.getFilesystemPath(), configPath);
        if (configFile.exists())
        {
            return configFile;
        }
        return null;
    }

    public void setConfigFile(IPath path)
    {
        setValue(CONFIG_FILE, path.toString());
    }
}
